name: test
on: push
jobs:
  log-date:
    runs-on: ubuntu-latest
    steps:
      - name: create date txt
        run: date >> date.txt
      - name: log dir
        run: ls -a
      - name: read date txt
        run: cat date.txt
  log-node-version:
    needs: log-date
    runs-on: ubuntu-latest
    steps:
      - name: log node version
        run: node --version
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: log node version
        run: node --version
  log-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
      - name: log README.md
        run: cat README.md
