name: test
on: push
jobs:
  log-date:
    runs-on: ubuntu-latest
    steps:
      - name: log date
        run: date
  log-node-version:
    runs-on: ubuntu-latest
    steps:
      - name: log node version
        run: node --version
